# Site settings
title: Alon Berman
twitter_username: a_ber
name: Alon Berman

# Build settings
markdown: kramdown

primarylinks:
 - title: GitHub
   url: https://github.com/alon-berman
 - title: StackOverflow
   url: https://stackoverflow.com/users/11845677/a-ber
 - title: LinkedIn
   url: https://www.linkedin.com/in/alon-berman-b2010ba1


skills:
 - Python
 - C
 - Azure Cloud
 - MATLAB
 - Terraform
 - Javascript
 - Microprocessors
 - RTOS / Linux / Windows
 - HTML
 - CSS
 - MVC
 - Wordpress
 
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2023
   subject: Computer Science
   school: College of Management Academics, Israel


roles:
 - title: Software Engineer
   start: 2019
   end: Ongoing
   employer: Vayyar
   description: As a software enginner at Vayyar, I was responsible to design, develop and maintain MVPs scalable infrastructure. The role included managing the development procedurs using Agile methodologies, defining key feautres and capabilities, and all the way to the hands-on development of the product.
   
 - title: Software Developer
   start: 2017
   end: 2019
   employer: Vayyar
   description: The role included
 
 - title: Full Stack Website Developer
   start: 2016
   end: 2017
   employer: Self Employed
   description: During my period as a Full Stack Website developer I was responsible to execute the entire development procedure, including Understanding clients requirements, Profile and characterize the website feautres and develop and deliver a fully working project on schedule.


github:
 - alon-berman/TempMonitor
 - alon-berman/Algorithm_Tester
 

intro: |
  I am a Software Engineer with over 5 years of hands on experience. During that time I have had the honor working on a wide spectrum of projects, applying top-notch software engineering principles and methodologies. <br/><br/>
  In my free time, I enjoy working on personal hardware-oriented projects in the IoT field, trade domain names and invest in crypto-currencies and NFTs.<br/><br/>
  In addition, I have been playing Classical Music on guitar for over 12 years. Music has a very special place in my life.
  

additionalinfo: |
   <strong>Python</strong>: Conceptualized the software requirements into software implementation. Took an extensive part in the entire software development life cycle (SDLC) — shifting the concentration from the problem to the solution. <br/> Was responsible to design, implement and maintain API interfaces, tools and applicatioמs for company-wide usage, Emphasized on OOP methodologies, code reuseability and modularity.<br/><br/>
   <strong>C</strong>: Designed and developed applications for different microprocessors using C Embedded, mainly for IoT purposes, focusing on resources management, clean, stable code and implementing different communication protocols such as MQTT, AMQP, TCP, HTTP, SPI and more.<br/><br/>
   <strong>MATLAB</strong> Developed C-Mex based RADAR communication API interfaces to be natively used by MATLAB client. In addition, developed and maintain regression test using MATLAB parallel computing, providing solid CI\CD infrastructure for different R&D teams. <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used Azure for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of Azure offerings, including Function Apps, Event Hub, Service Bus, PSQL, DPS and more.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, Node.js, and Angular.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with Git, TeamCity, GitHub Features etc. I have experience with an array of testing tools and technologies.<br/><br/>
   
